#! /bin/bash

export MYSQL_CONNECT=192.168.1.240:3306
export MYSQL_DATABASE=stocks
export MYSQL_PASSWORD=jipki7Y32iX5c
export MYSQL_USERNAME=reg

base="/root/github/diamond_hands"

{
if test "$1" = "EOD"
	then
		${base}/end_of_day
	else
		${base}/pre-get_prices
		${base}/get_price
		${base}/update_batches
	fi
} 2>&1 | logger -t get_price -i
