#! /bin/sh

. /opt/mylogin/stocks

echo ""

sqlsh -s'|' -d stocks 'select 
		account_held,
		format(sum(s.current_value_gbp),2) "Now",
		format(sum(s.current_value_gbp-t.total_cost_gbp),2) "Total Change",
		concat("(",format(sum(t.total_cost_gbp),2),")") "total cost",
		concat(format((sum(s.current_value_gbp-t.total_cost_gbp)/sum(t.total_cost_gbp))*100,2),"%") "total %age",
		format(sum(s.current_value_gbp-e.current_value_gbp),2) "Change",
		format((sum(s.current_value_gbp-e.current_value_gbp)/sum(e.current_value_gbp))*100,2)
	from trades t
	join spot_values e on(t.eod_spot_value_id = e.spot_value_id)
	join spot_values s on(t.spot_value_id = s.spot_value_id) group by 1' \
	\
	\
	'select "="' \
	\
	\
	'select
		"ALL",
		format(sum(s.current_value_gbp),2) "Now",
		format(sum(s.current_value_gbp-t.total_cost_gbp),2) "Total Change",
		concat("(",format(sum(t.total_cost_gbp),2),")") "total cost",
		concat(format((sum(s.current_value_gbp-t.total_cost_gbp)/sum(t.total_cost_gbp))*100,2),"%") "total %age",
		format(sum(s.current_value_gbp-e.current_value_gbp),2) "Change",
		format((sum(s.current_value_gbp-e.current_value_gbp)/sum(e.current_value_gbp))*100,2)
	from trades t
	join spot_values e on(t.eod_spot_value_id = e.spot_value_id)
	join spot_values s on(t.spot_value_id = s.spot_value_id)' | \
	\
	\
	awk -F'|' 'BEGIN {
		printf "%c[5;1m%-13s%11s%13s%13s%12s|%12s%11s%c[0m\n",
			27,"Account","Total Now","Total +/-","Initial","Total%age","Day +/-","Day %age",27
		}
		{
		if ($1=="=") print ""
		else {
			if (substr($5,1,1)=="-") col5="40;31;1"; else col5="40;32;1";
			if (substr($NF,1,1)=="-") col="40;31;1"; else col="40;32;1";
			if ($NF=="0.00") col="0"
			printf "%-13s%11s%c[%sm%13s%c[0m%13s%c[%sm%11s%c[0m |%c[%sm%12s%10s%%%c[0m\n",$1,$2,27,col5,$3,27,$4,27,col5,$5,27,27,col,$6,$7,27
			}
		}'

echo ""
