#! /bin/sh

. /opt/mylogin/stocks

echo ""

sqlsh -s'|' -d stocks 'select 
		ticker,
		format(sum(e.current_value_gbp),2) "Start",
		format(sum(s.current_value_gbp),2) "Now",
		format(sum(e.current_price),2) "SOD-Price",
		format(sum(s.current_price),2) "Price",
		format(sum(s.current_value_gbp-e.current_value_gbp),2) "Change",
		format((sum(s.current_value_gbp-e.current_value_gbp)/sum(e.current_value_gbp))*100,2)
	from trades t
	join spot_values e on(t.eod_spot_value_id = e.spot_value_id)
	join spot_values s on(t.spot_value_id = s.spot_value_id)
	where t.currency = "GBP"
	group by 1' \
	\
	'select "="' \
	\
	'select 
		"All GBP",
		format(sum(e.current_value_gbp),2) "Start",
		format(sum(s.current_value_gbp),2) "Now",
		format(sum(e.current_price),2) "SOD-Price",
		format(sum(s.current_price),2) "Price",
		format(sum(s.current_value_gbp-e.current_value_gbp),2) "Change",
		format((sum(s.current_value_gbp-e.current_value_gbp)/sum(e.current_value_gbp))*100,2)
	from trades t
	join spot_values e on(t.eod_spot_value_id = e.spot_value_id)
	join spot_values s on(t.spot_value_id = s.spot_value_id)
	where t.currency = "GBP"' \
	\
	'select "="' \
	\
	'select 
		ticker,
		format(sum(e.current_value_gbp),2) "Start",
		format(sum(s.current_value_gbp),2) "Now",
		format(sum(e.current_price),2) "SOD-Price",
		format(sum(s.current_price),2) "Price",
		format(sum(s.current_value_gbp-e.current_value_gbp),2) "Change",
		format((sum(s.current_value_gbp-e.current_value_gbp)/sum(e.current_value_gbp))*100,2)
	from trades t
	join spot_values e on(t.eod_spot_value_id = e.spot_value_id)
	join spot_values s on(t.spot_value_id = s.spot_value_id)
	where t.currency != "GBP"
	group by 1' \
	\
	'select "="' \
	\
	'select
		"Rest",
		format(sum(e.current_value_gbp),2) "Start",
		format(sum(s.current_value_gbp),2) "Now",
		format(sum(e.current_price),2) "SOD-Price",
		format(sum(s.current_price),2) "Price",
		format(sum(s.current_value_gbp-e.current_value_gbp),2) "Change",
		format((sum(s.current_value_gbp-e.current_value_gbp)/sum(e.current_value_gbp))*100,2)
	from trades t
	join spot_values e on(t.eod_spot_value_id = e.spot_value_id)
	join spot_values s on(t.spot_value_id = s.spot_value_id)
	where t.currency != "GBP"' \
	| awk -F'|' '{ 
		if ($1=="=") print ""
		else {
			if (substr($NF,1,1)=="-") col="40;31;1"; else col="40;32;1";
			printf "%-13s%13s%13s%13s%c[%sm%12s |%12s%10s%%%c[0m\n",$1,$2,$3,$4,27,col,$5,$6,$7,27
			}
		}'
