#! /bin/bash

. /opt/mylogin/stocks


tmp=$(mktemp)
while test 1
do 
	{
	echo -n $'\e[H\e[J'
	date
	echo "-----------------------------------------------"
	./day_movement_by_ticker
	echo ""
	echo "-----------------------------------------------"
	echo ""
	./day_movement_by_account
	} > ${tmp}

	cat ${tmp}
	rm -f ${tmp}
	sleep 10
done

