#! /bin/bash

export MYSQL_CONNECT=192.168.1.240:3306
export MYSQL_DATABASE=stocks
export MYSQL_PASSWORD=jipki7Y32iX5c
export MYSQL_USERNAME=reg

tmp=$(mktemp)
while test 1
do 
	{
	echo -n $'\e[H\e[J'
	date
	echo "-----------------------------------------------"
	./day_movement_by_ticker
	echo ""
	echo "-----------------------------------------------"
	echo ""
	./day_movement_by_account
	} > ${tmp}

	cat ${tmp}
	rm -f ${tmp}
	sleep 10
done

