#! /bin/sh

if test -f /usr/local/etc/stocks.login
	then
		. /usr/local/etc/stocks.login
	fi

base="/usr/local/diamond-hands"

{
cd ${base}
export PYTHONPATH=${base}
${base}/pre-get_prices
${base}/get_price
${base}/update_batches

if test -f /tmp/new_day
	then
		${base}/end_of_day
	fi

rm -f /tmp/new_day

} 2>&1 | ${base}/pylogger -i -t get_price -f local0
