#! /bin/sh

if test -f /usr/local/etc/stocks.login
	then
		. /usr/local/etc/stocks.login
	fi

base="/usr/local/diamond-hands"

{
if test "$1" = "EOD"
	then
		${base}/end_of_day
	else
		${base}/pre-get_prices
		${base}/get_price
		${base}/update_batches
	fi
} 2>&1 | ${base}/pylogger -i -t get_price -f local0
