#! /bin/sh

base="/usr/local/diamond-hands"

echo "EndOfDay"

${base}/pysqlsh 'update spot_values v join end_of_day eod using(spot_value_id)
	set v.end_of_day = 1 where v.end_of_day is NULL' \
\
	'update spot_values set end_of_day = 0 where end_of_day is NULL and batch < date(now())' \
\
	'update trades t join end_of_day_value v using(trade_id) set t.eod_spot_value_id = v.spot_value_id' \
	'update trades t join end_of_week_value v using(trade_id) set t.eow_spot_value_id = v.spot_value_id' \
\
	'delete from spot_values
		where not end_of_day
		and batch < date_sub(now(),interval 1 week)' \
\
	'delete from spot_rates
		where batch < date_sub(now(),interval 1 week)
		and batch not in (select batch from spot_values)' \
\
	'delete from spot_prices
		where spot_price_id not in (select spot_price_id from spot_values)
		and spot_price_id not in (select spot_price_id from spot_rates)'
