#! /bin/sh

base="/usr/local/diamond-hands"

echo "Pre-Prices"

${base}/pysqlsh 'insert into tickers(ticker)
	select distinct ticker
	from trades
	where ticker not in (select ticker from tickers)' \
 \
	'insert into tickers(ticker)
	select distinct concat("GBP",currency,"=X")
	from trades
	where currency != "GBP"
	and concat("GBP",currency,"=X") not in
		(select ticker from tickers)'
\
	'delete from tickers
		where ticker not in (select ticker from trades)
		and ticker not like "%=X"'
