#! /usr/bin/python3

import sys
import os

import MySQLdb as mdb

from MySQLdb.constants import FIELD_TYPE
import MySQLdb.converters


def convert_string(data):
    if isinstance(data, bytes):
        return data.decode("utf8")
    return data


my_conv = MySQLdb.converters.conversions.copy()
my_conv[FIELD_TYPE.VARCHAR] = convert_string
my_conv[FIELD_TYPE.CHAR] = convert_string
my_conv[FIELD_TYPE.STRING] = convert_string
my_conv[FIELD_TYPE.VAR_STRING] = convert_string
my_conv[FIELD_TYPE.DATETIME] = convert_string
my_conv[FIELD_TYPE.JSON] = convert_string
my_conv[FIELD_TYPE.TINY_BLOB] = convert_string
my_conv[FIELD_TYPE.MEDIUM_BLOB] = convert_string
my_conv[FIELD_TYPE.LONG_BLOB] = convert_string
my_conv[FIELD_TYPE.BLOB] = convert_string
my_conv[FIELD_TYPE.TINY] = convert_string
my_conv[FIELD_TYPE.DECIMAL] = convert_string
my_conv[FIELD_TYPE.NEWDECIMAL] = convert_string


def mysql_connect():
    """ Connect to MySQL based on ENV vars """
    sock = "/tmp/mysql.sock"
    host = None
    port = None
    if "MYSQL_CONNECT" in os.environ:
        conn = os.environ["MYSQL_CONNECT"]
        if conn.find("/") >= 0:
            sock = conn
        else:
            host = conn
            port = 3306
            if conn.find(":") >= 0:
                svr = conn.split(":")
                host = svr[0]
                port = int(svr[1])

    return mdb.connect(
        user=os.environ["MYSQL_USERNAME"],
        passwd=os.environ["MYSQL_PASSWORD"],
        unix_socket=sock,
        host=host,
        port=port,
        db=os.environ["MYSQL_DATABASE"],
        conv=my_conv,
        charset='utf8mb4',
        init_command='SET NAMES UTF8',
    )


cnx = mysql_connect()
cursor = cnx.cursor()

for sql in sys.argv[1:]:
    cnx.query(sql)
    if (res := cnx.store_result()) is not None:
        db_rows = res.fetch_row(maxrows=0, how=1)
        for row in db_rows:
           print("".join([ str(row[col]) for col in row]))
        ## print(json.dumps(db_rows,indent=3))
    else:
        cnx.commit()

cnx.close()
