#! /bin/sh

base="/usr/local/diamond-hands"

echo "Update"

${base}/pysqlsh 'insert into spot_rates
	select p.batch,substr(p.ticker,4,3),p.price,NULL,p.spot_price_id
	from spot_prices p
	left join spot_rates r on(substr(p.ticker,4,3)=r.currency and p.batch=r.batch)
	where p.ticker like "GBP%=X"
	and r.currency is NULL' \
 \
 \
	'insert into spot_rates
	select distinct batch,"GBP",1,NULL,NULL
	from spot_prices
	where batch not in (
		select batch from spot_rates where currency="GBP"
		)' \
 \
 \
	'insert into spot_values(trade_id,batch,current_price,current_exchange_rate,current_value_gbp,spot_price_id,spot_value_id)
		select t.trade_id,s.batch,s.price,r.exchange_rate,(s.price*t.quantity)/r.exchange_rate,s.spot_price_id,NULL
		from trades t
		join spot_prices s on(t.ticker=s.ticker and t.currency=s.currency)
		join spot_rates r on(s.currency=r.currency and s.batch = r.batch)
		where s.spot_price_id not in (select spot_price_id from spot_values)' \
 \
 \
	'update trades t join latest_values vv using(trade_id) set t.spot_value_id = vv.spot_value_id'
