#! /bin/sh

sqlsh 'create view latest_values as
	select v.* from spot_values v join (
		select max(batch) "batch",trade_id
		from spot_values
		group by 2
		) vv 
	on (v.batch=vv.batch and v.trade_id = vv.trade_id)' \
\
\
'create view latest_rates as 
	select r.* from spot_rates r join (
		select max(batch) "batch",currency
		from spot_rates group by currency
		) rr
	on (r.batch=rr.batch and r.currency=rr.currency)' \
\
\
'create view end_of_day_value as
	select v.* from spot_values v join (
		select max(batch) "batch",trade_id,date(batch)
		from spot_values
		where batch < date(now()) group by 2,3
	) vv on (v.batch=vv.batch and v.trade_id = vv.trade_id)' \
\
\
'create view end_of_week_value as
	select v.* from spot_values v join (
		select max(batch) "batch",trade_id,date(batch)
		from spot_values
		where end_of_day and WEEKDAY(batch) = 6
		group by 2,3
		) vv 
	on (v.batch=vv.batch and v.trade_id = vv.trade_id)' \
\
\
'create view current_value as
	select * from trades join spot_values using(spot_value_id,trade_id)' \
\
\
'create view end_of_day as
	select v.trade_id,date(v.batch),v.spot_value_id
	from spot_values v join (
		select max(batch) "batch",trade_id,date(batch)
		from spot_values
		where batch < date(now()) group by 2,3
		) vv 
	on (v.batch=vv.batch and v.trade_id = vv.trade_id)' \
\
'create view total_value as
	select date(batch) "date",sum(current_value_gbp) "total"
	from trades
	join spot_values using(trade_id)
	where spot_values.end_of_day
	group by 1
'
